#!/bin/bash
set -e

# Optional: Import test library
source dev-container-features-test-lib

# Definition specific tests
check "socat_installed" socat -V

# Simulate an MCP client already being connected inside the container (the
# precondition NOTES.md assumes), then run the appPort commands documented
# in NOTES.md, backgrounded (`&`) with a wait loop bounded by `timeout` so
# the test can run unattended instead of hanging. This only proves the relay
# is reachable from inside the container's network namespace; it does not
# prove the host can actually reach it through Docker's published port (a
# container-internal test script has no way to run curl from the host
# side). To check that too: run `devcontainer features test -f
# codebase-memory-mcp --skip-autogenerated --filter port-relay
# --preserve-test-containers .`, then `curl http://localhost:9749` from the
# host while the container is still up (scenarios.json's
# `appPort: ["9749:9749"]` publishes it there).
cat <<'SCRIPT' > /tmp/ui-notes-commands.sh
#!/bin/bash
set -e
# The feature's entrypoint runs `codebase-memory-mcp install --yes` in the
# background and can still be finishing it when this script starts; racing
# it here causes the binary's self-install/fingerprint-verification routine
# to fire again and evict whatever CBM session it collides with. Give it a
# fixed head start before touching the binary at all.
sleep 30
(tail -f /dev/null | codebase-memory-mcp > /tmp/mcp.log 2>&1 &)
# `--ui=true` only attaches a UI to an already-running MCP session; it exits
# immediately (successfully) if no session daemon exists yet, so wait for
# the daemon the line above spawns before calling it. Also run it in the
# foreground (no `&`) since it's a one-shot control command, not a server.
timeout 30 bash -c 'until pgrep -f cbm-daemon-internal > /dev/null 2>&1; do sleep 0.5; done'
codebase-memory-mcp --ui=true --port=9749
timeout 10 bash -c 'until curl -sf http://127.0.0.1:9749 > /dev/null 2>&1; do sleep 0.5; done'
socat TCP-LISTEN:9749,bind=$(hostname -I | awk '{print $1}'),fork,reuseaddr TCP:127.0.0.1:9749 &
sleep 1
curl -sf --max-time 2 -H "Host: localhost:9749" "http://$(hostname -I | awk '{print $1}'):9749/" > /dev/null
SCRIPT
chmod +x /tmp/ui-notes-commands.sh
check "ui_reachable_via_notes_commands" /tmp/ui-notes-commands.sh

# Report result
reportResults
