#!/bin/bash
set -e

# Optional: Import test library
source dev-container-features-test-lib

# Definition specific tests
check "socat_installed" socat -V

# Simulate an MCP client already being connected inside the container (the
# precondition NOTES.md assumes), then run the exact appPort one-liner
# documented in NOTES.md, unmodified. This only proves the relay is reachable
# from inside the container's network namespace; it does not prove the host
# can actually reach it through Docker's published port (a container-internal
# test script has no way to run curl from the host side). To check that too:
# run `devcontainer features test -f codebase-memory-mcp --skip-autogenerated
# --filter ui --preserve-test-containers .`, then `curl http://localhost:9749`
# from the host while the container is still up (scenarios.json's
# `appPort: ["9749:9749"]` publishes it there).
cat <<'SCRIPT' > /tmp/ui-notes-oneliner.sh
#!/bin/bash
set -e
(tail -f /dev/null | codebase-memory-mcp > /tmp/mcp.log 2>&1 &)
sleep 1
codebase-memory-mcp --ui=true --port=9749 && socat TCP-LISTEN:9749,bind=$(hostname -I | awk '{print $1}'),fork,reuseaddr TCP:127.0.0.1:9749 &
sleep 3
curl -sf --max-time 2 -H "Host: localhost:9749" "http://$(hostname -I | awk '{print $1}'):9749/" > /dev/null
SCRIPT
chmod +x /tmp/ui-notes-oneliner.sh
check "ui_reachable_via_notes_oneliner" /tmp/ui-notes-oneliner.sh

# Report result
reportResults
